export const columnsVI = ['ID', 'Version', 'Monto','Saldo', 'Detalle', 'Partidas']
export const dataKeyVI = ['id_version_presupuesto', 'version', 'monto', 'saldo', 'detalle', 'Partidas']
export const columnsPartidas = ['ID','Monto','Saldo', 'Detalle', 'Gastos']
export const dataKeyPartidas = ['id_partida','monto', 'saldo', 'detalle', 'Gastos']
export const columnsGastos = ['Código','Fecha','Detalle', 'Monto']
export const dataKeyGastos = ['id_gasto','fecha', 'detalle', 'monto']