export const columnsVI = ['ID', 'Version', 'Monto', 'Detalle', 'Partidas']
export const dataKeyVI = ['id_version_presupuesto', 'version', 'monto', 'detalle', 'Partidas']
export const columnsPartidas = ['ID', 'Monto', 'Gastos']
export const dataKeyPartidas = ['id_partida', 'monto', 'detalle']
export const columnsGastos = ['Código', 'Fecha', 'Detalle', 'Monto']
export const dataKeyGastos = ['id_gasto', 'fecha', 'detalle', 'monto']