# Generated by Django 4.2.4 on 2024-03-05 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='id_asistente_carnet',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='asistente',
            name='id_nombre_completo_fk',
            field=models.ForeignKey(db_column='id_nombre_completo_fk', on_delete=django.db.models.deletion.CASCADE, to='personas.nombrecompleto'),
        ),
    ]
