# Generated by Django 4.2.4 on 2024-04-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_asistente_id_asistente_carnet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistente',
            name='cedula',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
