# Generated by Django 4.2 on 2023-10-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0002_alter_academico_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="institucion",
            name="id_institucion",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
