# Generated by Django 4.2.4 on 2023-10-01 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_academico_foto'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='universidad',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='academico',
            name='id_area_especialidad_fk',
            field=models.ForeignKey(db_column='id_area_especialidad_fk', on_delete=django.db.models.deletion.CASCADE, to='personas.areaespecialidad'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='id_nombre_completo_fk',
            field=models.ForeignKey(db_column='id_nombre_completo_fk', on_delete=django.db.models.deletion.CASCADE, to='personas.nombrecompleto'),
        ),
        migrations.AlterField(
            model_name='academico',
            name='universidad_fk',
            field=models.ForeignKey(db_column='universidad_fk', on_delete=django.db.models.deletion.DO_NOTHING, to='personas.universidad'),
        ),
        migrations.AlterField(
            model_name='areaespecialidad',
            name='nombre',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='telefono',
            name='id_academico_fk',
            field=models.ForeignKey(db_column='id_academico_fk', on_delete=django.db.models.deletion.CASCADE, to='personas.academico'),
        ),
        migrations.AlterField(
            model_name='titulos',
            name='id_academico_fk',
            field=models.ForeignKey(db_column='id_academico_fk', on_delete=django.db.models.deletion.CASCADE, to='personas.academico'),
        ),
    ]
