# Generated by Django 4.2.4 on 2023-10-08 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0002_alter_areaespecialidad_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areaespecialidad',
            name='nombre',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
