# Generated by Django 4.2 on 2023-10-26 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0003_alter_institucion_id_institucion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="autor",
            name="id_nombre_completo_fk",
            field=models.ForeignKey(
                db_column="id_nombre_completo_fk",
                on_delete=django.db.models.deletion.CASCADE,
                to="personas.nombrecompleto",
            ),
        ),
    ]
