# Generated by Django 4.2.4 on 2024-05-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personas', '0003_alter_asistente_cedula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluador',
            name='correo',
            field=models.CharField(max_length=45, unique=True),
        ),
    ]
