# Generated by Django 4.2.4 on 2024-01-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organo_colegiado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organocolegiado',
            name='acuerdo_firme',
            field=models.IntegerField(),
        ),
    ]
