# Generated by Django 4.2.4 on 2024-04-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organo_colegiado', '0002_alter_organocolegiado_acuerdo_firme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='integrante',
            old_name='id_oficio_nombramiento_fk',
            new_name='id_oficio_fk',
        ),
        migrations.RemoveField(
            model_name='integrante',
            name='id',
        ),
        migrations.AddField(
            model_name='integrante',
            name='id_integrante',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='integrante',
            name='inicio_funciones',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
