# Generated by Django 4.2.4 on 2024-04-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organo_colegiado', '0003_rename_id_oficio_nombramiento_fk_integrante_id_oficio_fk_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='integrante',
            unique_together={('id_organo_colegiado_fk', 'id_integrante')},
        ),
        migrations.AddField(
            model_name='integrante',
            name='nombre_integrante',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='integrante',
            name='id_academico_fk',
        ),
    ]
