# Generated by Django 4.2.4 on 2024-04-29 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0013_alter_documento_detalle'),
        ('organo_colegiado', '0004_alter_integrante_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acta',
            name='id_documento_acta_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_proyecto.documento'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='id_convocatoria_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organo_colegiado.convocatoria'),
        ),
        migrations.AlterField(
            model_name='convocatoria',
            name='id_documento_convocatoria_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_proyecto.documento'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='id_acta_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organo_colegiado.acta'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='id_agenda_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organo_colegiado.agenda'),
        ),
        migrations.AlterField(
            model_name='sesion',
            name='id_organo_colegiado_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organo_colegiado.organocolegiado'),
        ),
    ]
