# Generated by Django 4.2.4 on 2024-05-01 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0013_alter_documento_detalle'),
        ('organo_colegiado', '0005_alter_acta_id_documento_acta_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuerdo',
            name='id_documento_acuerdo_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_proyecto.documento'),
        ),
        migrations.AlterField(
            model_name='acuerdo',
            name='id_oficio_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_proyecto.oficio'),
        ),
        migrations.AlterField(
            model_name='acuerdo',
            name='id_seguimiento_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organo_colegiado.seguimiento'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='id_documento_seguimiento_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version_proyecto.documento'),
        ),
    ]
