"""
Django settings for django_files project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u*b+_s_c!7e67rw*u9(8mo5xte9r3hjftal*x7st83wx=z8ok)'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

CORS_ALLOW_ALL_ORIGINS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',                 # <- Agreado 
    'rest_framework',              # <- Agreado
    'rest_framework.authtoken',    # <- Agreado
    'coreapi',                     # <- Agreado
    'informe',                     # <- Agreado
    'organo_colegiado',            # <- Agreado
    'personas',                    # <- Agreado
    'presupuesto',                 # <- Agreado
    'producto',                    # <- Agreado
    'propuesta_proyecto',          # <- Agreado
    'version_proyecto',            # <- Agreado
    'usuario_personalizado',       # <- Agreado
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',                 # <- Agregado
    'django.middleware.locale.LocaleMiddleware',             # <- Agregado
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'django_files.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'personas', 'templates'),
        os.path.join(BASE_DIR, 'propuesta_proyecto', 'templates'),
        os.path.join(BASE_DIR, 'presupuesto', 'templates'),
        os.path.join(BASE_DIR, 'version_proyecto', 'templates'),
        os.path.join(BASE_DIR, 'producto', 'templates'),
        os.path.join(BASE_DIR, 'usuario_personalizado', 'templates'),
        os.path.join(BASE_DIR, 'informe', 'templates'),
        os.path.join(BASE_DIR, 'organo_colegiado', 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'django_files.wsgi.application'
CORS_ALLOW_ORIGINS = [ 
    "http://localhost:5173",
]

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_USER_MODEL = 'usuario_personalizado.Usuario'

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/


LANGUAGE_CODE = 'es'

LANGUAGES = [
    ('es', 'Spanish'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Documentos 
MEDIA_URL = '/media/'                        # Cuando un usuario carga un archivo, se generará una URL que comienza con MEDIA_URL. 
                                             # Ej:  '/documentos/docPropuesta1.jpg'.
MEDIA_ROOT = BASE_DIR / 'media'              # Define la ubicación en el sistema de archivos donde se almacenarán los archivos. 

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com' # Servidor SMTP de Gmail
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'cimpa.siap@gmail.com'
EMAIL_HOST_PASSWORD = 'clzjmmlwtanatyil'
EMAIL_DEFAULT_SENDER = 'brandonbadilla143@gmail.com'
