
### Crear usuario

POST http://127.0.0.1:8000/signup 
Authorization: token dd2dc2f7ddffd73c0af2277eff3856214bd0c6fa
Content-Type: application/json

{
  "correo": "root@root.com", 
  "password": "root", 
}


### Inicio de sesion

POST http://127.0.0.1:8000/login
Content-Type: application/json

{ "correo": "root@root.com", "password": "root" }

### Probar acceso a views

GET http://127.0.0.1:8000/informe/informes/
Content-Type: application/json
Authorization: token dd2dc2f7ddffd73c0af2277eff3856214bd0c6fa

### Obtener usuarios

GET http://127.0.0.1:8000/obtener_usuarios
Authorization: Token dd2dc2f7ddffd73c0af2277eff3856214bd0c6fa
Content-Type: application/json

### Actualizar usuario 

PUT http://127.0.0.1:8000/actualizar_usuario/primuri/ HTTP/1.1
Authorization: Token dd2dc2f7ddffd73c0af2277eff3856214bd0c6fa
Content-Type: application/json

{
    "username": "primuri",
    "first_name": "pri",
    "last_name": "muri",
    "password": "pbkdf2_sha256$600000$MuifscRqLOH0Bb6uNQ4QQT$TOkmYsZuMrRsiyvfEkxauRMqVs4GQb3DUtFmYb/WRGY="
}

### Eliminar usuario

DELETE http://127.0.0.1:8000/eliminar_usuario/primurasi/ HTTP/1.1
Authorization: Token dd2dc2f7ddffd73c0af2277eff3856214bd0c6fa