# Generated by Django 4.2.4 on 2023-10-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuesta_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoasociado',
            name='documento',
            field=models.FileField(upload_to='media/'),
        ),
    ]
