# Generated by Django 4.2.4 on 2024-04-25 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propuesta_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaboradorprincipal',
            name='id_vigencia_fk',
            field=models.ForeignKey(blank=True, db_column='id_vigencia_fk', null=True, on_delete=django.db.models.deletion.PROTECT, to='propuesta_proyecto.vigencia'),
        ),
    ]
