# Generated by Django 4.2.4 on 2023-10-06 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('propuesta_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propuestaproyecto',
            old_name='detalle',
            new_name='objetivo_general',
        ),
        migrations.AlterField(
            model_name='colaboradorprincipal',
            name='id_vigencia_fk',
            field=models.ForeignKey(blank=True, db_column='id_vigencia_fk', null=True, on_delete=django.db.models.deletion.PROTECT, to='propuesta_proyecto.vigencia'),
        ),
        migrations.AlterField(
            model_name='propuestaproyecto',
            name='descripcion',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='vigencia',
            name='fecha_fin',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vigencia',
            name='fecha_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
