# Generated by Django 4.2 on 2023-10-23 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("propuesta_proyecto", "0002_alter_documentoasociado_documento"),
    ]

    operations = [
        migrations.AlterField(
            model_name="colaboradorprincipal",
            name="id_vigencia_fk",
            field=models.ForeignKey(
                blank=True,
                db_column="id_vigencia_fk",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="propuesta_proyecto.vigencia",
            ),
        ),
        migrations.AlterField(
            model_name="documentoasociado",
            name="id_codigo_cimpa_fk",
            field=models.ForeignKey(
                db_column="id_codigo_cimpa_fk",
                on_delete=django.db.models.deletion.CASCADE,
                to="propuesta_proyecto.propuestaproyecto",
            ),
        ),
        migrations.AlterField(
            model_name="propuestaproyecto",
            name="id_colaborador_principal_fk",
            field=models.ForeignKey(
                db_column="id_colaborador_principal_fk",
                on_delete=django.db.models.deletion.CASCADE,
                to="propuesta_proyecto.colaboradorprincipal",
            ),
        ),
    ]
