# Generated by Django 4.2.4 on 2023-10-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('propuesta_proyecto', '0002_rename_detalle_propuestaproyecto_objetivo_general_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propuestaproyecto',
            name='objetivo_general',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
