# Generated by Django 4.2 on 2023-10-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "propuesta_proyecto",
            "0003_alter_colaboradorprincipal_id_vigencia_fk_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="propuestaproyecto",
            name="id_codigo_cimpa",
            field=models.AutoField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
