# Generated by Django 4.2 on 2023-10-24 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("propuesta_proyecto", "0004_alter_propuestaproyecto_id_codigo_cimpa"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propuestaproyecto",
            name="id_codigo_cimpa",
            field=models.CharField(max_length=45, primary_key=True, serialize=False),
        ),
    ]
