# Generated by Django 4.2.4 on 2023-10-11 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('version_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id_informe', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(max_length=64)),
                ('tipo', models.CharField(max_length=45)),
                ('fecha_presentacion', models.DateTimeField()),
                ('fecha_debe_presentar', models.DateTimeField()),
                ('id_version_proyecto_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='version_proyecto.versionproyecto')),
            ],
        ),
        migrations.CreateModel(
            name='VersionInforme',
            fields=[
                ('id_version_informe', models.AutoField(primary_key=True, serialize=False)),
                ('numero_version', models.CharField(max_length=45)),
                ('fecha_presentacion', models.DateTimeField()),
                ('id_documento_informe_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='version_proyecto.documento')),
                ('id_evaluacion_cc_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='version_proyecto.evaluacioncc')),
                ('id_informe_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informe.informe')),
                ('id_oficio_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='version_proyecto.oficio')),
            ],
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id_accion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('origen', models.CharField(max_length=192)),
                ('destino', models.CharField(max_length=192)),
                ('estado', models.CharField(max_length=155)),
                ('id_documento_accion_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='version_proyecto.documento')),
                ('id_version_informe_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informe.versioninforme')),
            ],
        ),
    ]
