# Generated by Django 4.2.4 on 2023-10-15 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0001_initial'),
        ('informe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='versioninforme',
            name='id_evaluacion_cc_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='version_proyecto.evaluacioncc'),
        ),
    ]
