# Generated by Django 4.2.4 on 2024-05-23 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('version_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoFinanciero',
            fields=[
                ('id_codigo_financiero', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'codigo_financiero',
            },
        ),
        migrations.CreateModel(
            name='EnteFinanciero',
            fields=[
                ('id_ente_financiero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'ente_financiero',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'factura',
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id_presupuesto', models.AutoField(primary_key=True, serialize=False)),
                ('anio_aprobacion', models.IntegerField()),
                ('tipo_presupuesto', models.CharField(default='', max_length=255)),
                ('id_codigo_financiero_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuesto.codigofinanciero')),
                ('id_codigo_vi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='version_proyecto.proyecto')),
                ('id_ente_financiero_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuesto.entefinanciero')),
                ('id_oficio_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='version_proyecto.oficio')),
                ('id_version_proyecto_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='version_proyecto.versionproyecto')),
            ],
            options={
                'db_table': 'presupuesto',
            },
        ),
        migrations.CreateModel(
            name='ProductoServicio',
            fields=[
                ('id_producto_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'producto_servicio',
            },
        ),
        migrations.CreateModel(
            name='VersionPresupuesto',
            fields=[
                ('id_version_presupuesto', models.AutoField(primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=45)),
                ('monto', models.CharField(max_length=45)),
                ('fecha', models.DateTimeField()),
                ('detalle', models.CharField(max_length=255, null=True)),
                ('id_presupuesto_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuesto.presupuesto')),
            ],
            options={
                'db_table': 'version_presupuesto',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id_cedula_proveedor', models.CharField(max_length=11, primary_key=True, serialize=False, unique=True)),
                ('tipo', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=64)),
                ('nombre', models.CharField(max_length=128)),
                ('telefono', models.CharField(max_length=45)),
                ('id_documento_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='version_proyecto.documento')),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id_partida', models.AutoField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_version_presupuesto_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuesto.versionpresupuesto')),
            ],
            options={
                'db_table': 'partida',
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id_gasto', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField()),
                ('detalle', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_documento_fk', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='version_proyecto.documento')),
                ('id_factura_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuesto.factura')),
                ('id_partida_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuesto.partida')),
            ],
            options={
                'db_table': 'gasto',
            },
        ),
        migrations.AddField(
            model_name='factura',
            name='id_cedula_proveedor_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuesto.proveedor'),
        ),
        migrations.AddField(
            model_name='factura',
            name='id_producto_servicio_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='presupuesto.productoservicio'),
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id_numero', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('banco', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=45)),
                ('moneda', models.CharField(max_length=45)),
                ('cuenta_principal', models.CharField(max_length=45)),
                ('id_proveedor_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presupuesto.proveedor')),
            ],
            options={
                'db_table': 'cuenta_bancaria',
                'unique_together': {('id_numero', 'banco', 'tipo', 'moneda', 'cuenta_principal', 'id_proveedor_fk')},
            },
        ),
    ]
