# Generated by Django 4.2.4 on 2023-10-22 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='id_proveedor_fk',
            field=models.ForeignKey(db_column='id_proveedor_fk', on_delete=django.db.models.deletion.CASCADE, to='presupuesto.proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id_cedula_proveedor',
            field=models.CharField(max_length=11, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='cuentabancaria',
            unique_together={('banco', 'tipo', 'moneda', 'cuenta_principal', 'id_proveedor_fk')},
        ),
    ]
