# Generated by Django 4.2.4 on 2023-10-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='tipo',
            field=models.CharField(default='null', max_length=45),
            preserve_default=False,
        ),
    ]
