# Generated by Django 4.2.4 on 2024-03-15 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0006_merge_20240202_1937'),
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gasto',
            name='tipo',
        ),
        migrations.AddField(
            model_name='gasto',
            name='id_documento_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='version_proyecto.documento'),
        ),
        migrations.AlterField(
            model_name='productoservicio',
            name='id_producto_servicio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
