# Generated by Django 4.2.4 on 2023-10-27 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoFinanciero',
            fields=[
                ('id_codigo_financiero', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'codigo_financiero',
            },
        ),
        migrations.RemoveField(
            model_name='presupuesto',
            name='codigo_financiero',
        ),
        migrations.AlterField(
            model_name='entefinanciero',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='id_codigo_financiero_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='presupuesto.codigofinanciero'),
            preserve_default=False,
        ),
    ]
