# Generated by Django 4.2.4 on 2023-10-30 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0001_initial'),
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='presupuesto',
            name='id_version_proyecto_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='version_proyecto.versionproyecto'),
            preserve_default=False,
        ),
    ]
