# Generated by Django 4.2.4 on 2024-03-15 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_remove_gasto_tipo_gasto_id_documento_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoservicio',
            name='id_producto_servicio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
