# Generated by Django 4.2.4 on 2023-10-25 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0001_initial'),
        ('presupuesto', '0002_proveedor_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='id_documento_fk',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='version_proyecto.documento'),
            preserve_default=False,
        ),
    ]
