# Generated by Django 4.2.4 on 2024-03-15 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_remove_gasto_tipo_gasto_id_documento_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='id_numero',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
