# Generated by Django 4.2.4 on 2023-10-27 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0002_codigofinanciero_and_more'),
        ('presupuesto', '0002_proveedor_tipo'),
    ]

    operations = [
    ]
