# Generated by Django 4.2.4 on 2023-10-27 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_merge_20231027_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codigofinanciero',
            name='codigo',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
