# Generated by Django 4.2.4 on 2023-10-25 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0001_initial'),
        ('presupuesto', '0003_proveedor_id_documento_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='id_documento_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='version_proyecto.documento'),
        ),
    ]
