# Generated by Django 4.2.4 on 2024-03-18 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_alter_cuentabancaria_id_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoservicio',
            name='detalle',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
