# Generated by Django 4.2 on 2023-10-29 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("presupuesto", "0004_alter_codigofinanciero_codigo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cuentabancaria",
            name="id_proveedor_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="presupuesto.proveedor"
            ),
        ),
    ]
