# Generated by Django 4.2.4 on 2024-04-19 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0004_alter_productoservicio_detalle'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cuentabancaria',
            unique_together={('id_numero', 'banco', 'tipo', 'moneda', 'cuenta_principal', 'id_proveedor_fk')},
        ),
    ]
