# Generated by Django 4.2.4 on 2023-10-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0004_alter_proveedor_id_documento_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='cuenta_principal',
            field=models.CharField(max_length=45),
        ),
    ]
