# Generated by Django 4.2.4 on 2024-04-29 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0005_alter_cuentabancaria_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='versionpresupuesto',
            name='saldo',
        ),
    ]
