# Generated by Django 4.2.4 on 2024-05-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0006_remove_versionpresupuesto_saldo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuesto',
            name='id_tipo_presupuesto_fk',
        ),
        migrations.AddField(
            model_name='presupuesto',
            name='tipo_presupuesto',
            field=models.CharField(default='', max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='TipoPresupuesto',
        ),
    ]
