# Generated by Django 4.2.4 on 2024-05-20 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0007_remove_presupuesto_id_tipo_presupuesto_fk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuesto',
            name='tipo_presupuesto',
            field=models.CharField(default='', max_length=255),
        ),
    ]
