# Generated by Django 4.2.4 on 2023-09-23 02:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaEvaluacion',
            fields=[
                ('id_pregunta_evaluacion', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.CharField(max_length=556)),
                ('respuesta', models.CharField(max_length=128)),
                ('id_evaluacion_fk', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='version_proyecto.evaluacion')),
            ],
            options={
                'db_table': 'pregunta_evaluacion',
            },
        ),
    ]
