# Generated by Django 4.2.4 on 2023-10-22 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='ruta_archivo',
            field=models.FileField(unique=True, upload_to='media/'),
        ),
    ]
