# Generated by Django 4.2.4 on 2024-01-07 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='id_version_proyecto_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='version_proyecto.versionproyecto'),
        ),
    ]
