# Generated by Django 4.2.4 on 2024-01-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluacion',
            old_name='id_documento_evualuacion_fk',
            new_name='id_documento_evaluacion_fk',
        ),
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.FileField(max_length=500, upload_to='media/documentos/'),
        ),
    ]
