# Generated by Django 4.2 on 2023-10-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("version_proyecto", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="versionproyecto", name="id_evaluacion_cc_fk",
        ),
    ]
