# Generated by Django 4.2.4 on 2023-10-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oficio',
            name='ruta_archivo',
            field=models.FileField(upload_to='media/oficios'),
        ),
        migrations.AlterUniqueTogether(
            name='oficio',
            unique_together={('ruta_archivo', 'id_oficio')},
        ),
    ]
