# Generated by Django 4.2 on 2023-10-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("version_proyecto", "0002_remove_versionproyecto_id_evaluacion_cc_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oficio",
            name="ruta_archivo",
            field=models.FileField(upload_to="media/"),
        ),
    ]
