# Generated by Django 4.2.4 on 2024-01-16 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0002_alter_evaluacion_id_version_proyecto_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='id_documento_evaluacion_fk',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='version_proyecto.documento'),
        ),
    ]
