# Generated by Django 4.2.4 on 2024-01-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0003_alter_evaluacion_id_documento_evaluacion_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion',
            name='detalle',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
