# Generated by Django 4.2 on 2023-10-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("version_proyecto", "0003_alter_oficio_ruta_archivo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="documento",
            field=models.FileField(upload_to="media/productos/"),
        ),
        migrations.AlterField(
            model_name="oficio",
            name="ruta_archivo",
            field=models.FileField(upload_to="media/proyectos/"),
        ),
    ]
