# Generated by Django 4.2 on 2023-10-22 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("version_proyecto", "0004_alter_documento_ruta_archivo_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documento",
            name="documento",
            field=models.FileField(upload_to="media/documentos/"),
        ),
        migrations.AlterField(
            model_name="oficio",
            name="ruta_archivo",
            field=models.FileField(upload_to="media/oficios/"),
        ),
    ]
