# Generated by Django 4.2.4 on 2024-01-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0004_alter_evaluacion_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='documento',
            field=models.FileField(max_length=500, null=True, upload_to='media/documentos/'),
        ),
    ]
