# Generated by Django 4.2.4 on 2024-02-02 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0003_respuestaevaluacion_delete_preguntaevaluacion'),
        ('version_proyecto', '0005_alter_documento_documento'),
    ]

    operations = [
    ]
