# Generated by Django 4.2 on 2023-10-24 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("version_proyecto", "0005_alter_documento_ruta_archivo_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="versionproyecto",
            unique_together={("id_codigo_vi_fk", "numero_version")},
        ),
    ]
