# Generated by Django 4.2 on 2023-10-29 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("version_proyecto", "0006_alter_versionproyecto_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="documento", old_name="ruta_archivo", new_name="documento",
        ),
    ]
