# Generated by Django 4.2.4 on 2024-04-25 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0006_merge_20240202_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designacionasistente',
            name='id_documento_inopia_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='version_proyecto.documento'),
        ),
    ]
