# Generated by Django 4.2.4 on 2024-04-25 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0009_alter_evaluacioncc_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacioncc',
            name='id_documento_evualuacion_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='version_proyecto.documento'),
        ),
    ]
