# Generated by Django 4.2.4 on 2024-04-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0011_alter_documento_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
