# Generated by Django 4.2.4 on 2024-04-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version_proyecto', '0012_alter_documento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='detalle',
            field=models.CharField(blank=True, max_length=360, null=True),
        ),
    ]
