# Generated by Django 4.2.4 on 2023-10-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_personalizado', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
