# Generated by Django 4.2.4 on 2023-09-26 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario_personalizado', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='segundo_apellido',
        ),
    ]
