# Generated by Django 4.2.4 on 2024-01-06 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='doi',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='isbn',
            field=models.CharField(max_length=255),
        ),
    ]
