# Generated by Django 4.2 on 2023-10-22 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producto", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="area",
            name="id_area",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="evento",
            name="id_evento",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="producto",
            name="id_producto",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="software",
            name="id_software",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
