# Generated by Django 4.2 on 2023-10-25 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("producto", "0002_alter_area_id_area_alter_evento_id_evento_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="id_version_proyecto",
            new_name="id_version_proyecto_fk",
        ),
    ]
