# Generated by Django 4.2.4 on 2024-04-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_alter_articulo_observaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='enlace',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
