# Generated by Django 4.2 on 2023-10-25 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("version_proyecto", "0006_alter_versionproyecto_unique_together"),
        ("producto", "0003_rename_id_version_proyecto_producto_id_version_proyecto_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="id_version_proyecto_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="version_proyecto.versionproyecto",
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="id_producto_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="producto.producto"
            ),
        ),
    ]
