# Generated by Django 4.2 on 2023-10-25 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("version_proyecto", "0006_alter_versionproyecto_unique_together"),
        ("producto", "0004_alter_producto_id_version_proyecto_fk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="software",
            name="id_documento_documentacion_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="version_proyecto.documento",
            ),
        ),
    ]
