# Generated by Django 4.2 on 2023-10-26 07:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0003_alter_institucion_id_institucion"),
        ("version_proyecto", "0006_alter_versionproyecto_unique_together"),
        ("producto", "0005_alter_software_id_documento_documentacion_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="id_autor_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="personas.autor"
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="id_documento_articulo_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="version_proyecto.documento",
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="id_producto_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="producto.producto"
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="id_revista_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="producto.revista"
            ),
        ),
    ]
