# Generated by Django 4.2 on 2023-10-26 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("personas", "0004_alter_autor_id_nombre_completo_fk"),
        ("version_proyecto", "0006_alter_versionproyecto_unique_together"),
        ("producto", "0006_alter_articulo_id_autor_fk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="id_autor_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="personas.autor"
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="id_documento_articulo_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="version_proyecto.documento",
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="id_producto_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="producto.producto"
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="id_revista_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="producto.revista"
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="id_documento_documentacion_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="version_proyecto.documento",
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="id_producto_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="producto.producto"
            ),
        ),
    ]
