# Generated by Django 4.2 on 2023-10-26 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("version_proyecto", "0006_alter_versionproyecto_unique_together"),
        ("producto", "0007_alter_articulo_id_autor_fk_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="id_version_proyecto_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="version_proyecto.versionproyecto",
            ),
        ),
    ]
