# Generated by Django 4.2 on 2023-10-26 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("version_proyecto", "0006_alter_versionproyecto_unique_together"),
        ("personas", "0004_alter_autor_id_nombre_completo_fk"),
        ("producto", "0008_alter_producto_id_version_proyecto_fk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articulo",
            name="id_autor_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="personas.autor"
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="id_documento_articulo_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="version_proyecto.documento",
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="id_producto_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="producto.producto"
            ),
        ),
        migrations.AlterField(
            model_name="articulo",
            name="id_revista_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="producto.revista"
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="id_area_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="producto.area"
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="id_institucion_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="personas.institucion"
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="id_oficio_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="version_proyecto.oficio",
            ),
        ),
        migrations.AlterField(
            model_name="evento",
            name="id_producto_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="producto.producto"
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="id_version_proyecto_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="version_proyecto.versionproyecto",
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="id_documento_documentacion_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="version_proyecto.documento",
            ),
        ),
        migrations.AlterField(
            model_name="software",
            name="id_producto_fk",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="producto.producto"
            ),
        ),
    ]
