# Generated by Django 4.2 on 2023-10-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("producto", "0009_alter_articulo_id_autor_fk_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="articulo",
            name="observaciones",
            field=models.TextField(blank=True, null=True),
        ),
    ]
